// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itknizsjtsjiughxitwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0a25penNqdHNqaXVnaHhpdHdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDQ0NDIsImV4cCI6MjA3MTc4MDQ0Mn0.vvLX0qrJQmoK0QvUP2a7atRba3msFSjcPz_G68ux1KM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});